version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: diagram-assistant
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --timeout-keep-alive 300
    restart: unless-stopped